service: mongodb-python
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  endpointType: REGIONAL

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    #When there are larger dependencies
#     dockerizePip: true
#     zip: true
    layer:
      name: python-pymongo-dnspython
      description: "Layer which contains pymongo and dnspython library"
      compatibleRuntimes:
        - python3.8

package:
  patterns:
    - "!**/*"
    - "*.py"

functions:
  - ${file(yml/functions/addSensorType.yml)}
  - ${file(yml/functions/deleteSensorType.yml)}
